unclassified:
  location:
    url: "https://jenkins.jkops.me"

jobs:
  - file: "/opt/jenkins-files/multibranch-pipeline-jobs/infra-jenkins/infra-jenkins-terraform-validation.groovy"
  - file: "/opt/jenkins-files/multibranch-pipeline-jobs/tf-gcp-infra/tf-gcp-infra-terraform-validation.groovy"
  - file: "/opt/jenkins-files/multibranch-pipeline-jobs/static-site/static-site-docker-image.groovy"
  - file: "/opt/jenkins-files/multibranch-pipeline-jobs/webapp-hello-world/healthz-api-docker-image.groovy"
  - file: "/opt/jenkins-files/multibranch-pipeline-jobs/healthz-database-migration/healthz-db-migration-docker-image.groovy"
